# Generated by Django 4.2.7 on 2023-11-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='task',
            field=models.CharField(blank=True, default='empty', max_length=1000, null=True),
        ),
    ]
